# Generated by Django 2.1.7 on 2019-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('Summary', models.TextField(max_length=250, null=True)),
                ('pre_movie', models.TextField(null=True)),
                ('Headlines', models.TextField(max_length=450, null=True)),
                ('user_number', models.IntegerField(default=0)),
                ('course_section_number', models.IntegerField(blank=True, default=0, null=True)),
                ('total_time_of_course', models.IntegerField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, max_length=450, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('all_text_content', models.TextField(blank=True, null=True)),
                ('exam', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
