# Generated by Django 2.1.7 on 2019-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20190508_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Headlines',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_movie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
