# Generated by Django 2.1.7 on 2019-05-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_auto_20190508_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Summary',
            new_name='summary',
        ),
    ]
