# Generated by Django 2.1.7 on 2019-05-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_auto_20190508_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_main_fields',
            new_name='course_main_field',
        ),
    ]
