# Generated by Django 2.1.7 on 2019-05-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_auto_20190508_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='who_has_what',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('last_pass_section', models.IntegerField(default=0)),
                ('course_completed', models.IntegerField(default=False)),
                ('course_finished_time', models.TimeField(blank=True, null=True)),
                ('course_teacher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fk_student', to='course_app.course')),
            ],
        ),
    ]
