# Generated by Django 2.1.7 on 2019-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_who_has_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(default='no_Name', max_length=50, unique=True),
        ),
    ]
