# Generated by Django 2.1.7 on 2019-05-12 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0008_auto_20190512_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='who_has_what',
            name='course_teacher',
        ),
        migrations.AddField(
            model_name='who_has_what',
            name='course_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fk_course', to='course_app.course'),
        ),
        migrations.AddField(
            model_name='who_has_what',
            name='course_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fk_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
