# Generated by Django 2.1.7 on 2019-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_auto_20190512_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(default='no_Name', max_length=50),
        ),
    ]
