# Generated by Django 2.1.7 on 2019-05-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0011_course_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='user_counter',
        ),
    ]
