# Generated by Django 2.1.7 on 2019-05-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0014_section_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=-1)),
                ('question', models.TextField(blank=True, max_length=300, null=True)),
                ('choice1', models.TextField(blank=True, max_length=200, null=True)),
                ('choice2', models.TextField(blank=True, max_length=200, null=True)),
                ('choice3', models.TextField(blank=True, max_length=200, null=True)),
                ('choice4', models.TextField(blank=True, max_length=200, null=True)),
                ('true_choice', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='who_has_what',
            name='total_grade',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='movie',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='who_has_what',
            name='grade',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question_exam',
            name='whitch_section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fk_section', to='course_app.section'),
        ),
    ]
