# Generated by Django 2.1.7 on 2019-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0015_auto_20190513_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who_has_what',
            name='course_completed',
            field=models.BooleanField(default=False),
        ),
    ]
