# Generated by Django 2.1.7 on 2019-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0016_auto_20190514_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='file',
        ),
        migrations.AddField(
            model_name='section',
            name='picture',
            field=models.ImageField(blank=True, default='folanja/images.png', null=True, upload_to='folanja/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='movie',
            field=models.TextField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
