# Generated by Django 2.1.7 on 2019-05-14 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0018_remove_section_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='picture',
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fkcourse', to='course_app.course'),
        ),
        migrations.AddField(
            model_name='section',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='anja/'),
        ),
    ]
