# Generated by Django 2.1.7 on 2019-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0019_auto_20190514_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/anja/'),
        ),
    ]
