# Generated by Django 2.1.7 on 2019-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0020_auto_20190515_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='anja/'),
        ),
    ]
