# Generated by Django 2.1.7 on 2019-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0022_auto_20190515_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='folanja/images.png', null=True, upload_to='folanja/'),
        ),
    ]
