# Generated by Django 2.1.7 on 2019-06-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0023_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who_has_what',
            name='course_finished_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
