# Generated by Django 2.1.7 on 2019-07-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0024_auto_20190607_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='movie',
        ),
        migrations.AddField(
            model_name='section',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
