# Generated by Django 2.1.7 on 2019-07-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0026_auto_20190708_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie_link',
        ),
    ]
