# Generated by Django 2.1.7 on 2019-07-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0027_delete_movie_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='who_has_what',
            name='last_time_question_req',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
