# Generated by Django 2.1.7 on 2019-07-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0028_who_has_what_last_time_question_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who_has_what',
            name='grade',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='who_has_what',
            name='last_time_question_req',
            field=models.TextField(blank=True, default='', max_length=20, null=True),
        ),
    ]
