# Generated by Django 2.1.7 on 2019-07-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0029_auto_20190710_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Headlines',
        ),
        migrations.RemoveField(
            model_name='course',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pre_movie',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ref',
        ),
        migrations.AddField(
            model_name='section',
            name='detail',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
