# Generated by Django 2.1.7 on 2019-07-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0030_auto_20190712_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='all_text_content',
        ),
    ]
