# Generated by Django 2.1.7 on 2019-07-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0031_remove_course_all_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_number',
        ),
    ]
