# Generated by Django 2.1.7 on 2019-07-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0032_remove_course_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='picture',
        ),
    ]
