# Generated by Django 2.1.7 on 2019-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0033_remove_course_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='folanja/images.png', null=True, upload_to='folanja/'),
        ),
    ]
