# Generated by Django 2.1.7 on 2019-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0034_course_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_pull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='anja/')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='file',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
