# Generated by Django 2.1.7 on 2019-06-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_file_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_file',
            name='picture',
        ),
        migrations.AddField(
            model_name='image_file',
            name='bina',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
