# Generated by Django 2.1.7 on 2019-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_file_test', '0002_auto_20190604_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_file',
            name='bina',
        ),
        migrations.AddField(
            model_name='image_file',
            name='picture',
            field=models.ImageField(blank=True, default='folanja/images.png', null=True, upload_to='folanja/temp_image_dir/'),
        ),
        migrations.AlterField(
            model_name='image_file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='folanja/temp_file_dir/'),
        ),
    ]
