# Generated by Django 2.1.7 on 2019-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_file_test', '0004_remove_image_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_file',
            name='picture',
            field=models.FileField(blank=True, default='folanja/images.png', null=True, upload_to='folanja/temp_image_dir/'),
        ),
    ]
