# Generated by Django 2.1.7 on 2019-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_file_test', '0005_auto_20190608_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(default='no_Name', max_length=50)),
                ('movie', models.FileField(default='no_Name', max_length=50, upload_to='')),
                ('msg', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
