# Generated by Django 2.1.7 on 2019-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_file_test', '0006_movie_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_link',
            name='msg',
        ),
        migrations.AddField(
            model_name='movie_link',
            name='section_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
