# Generated by Django 2.1.7 on 2019-07-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_file_test', '0007_auto_20190708_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_link',
            old_name='discription',
            new_name='name',
        ),
    ]
