# Generated by Django 2.1.7 on 2019-07-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_app', '0002_remove_aboutus_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(default='no_Name', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='no_Name', max_length=50)),
                ('explanation', models.TextField(default='no_Name', max_length=5000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='address',
            field=models.TextField(default='no_Name', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone',
            field=models.TextField(default='no_Name', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
