# Generated by Django 2.1.7 on 2019-07-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_app', '0005_remove_contactus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
