# Generated by Django 2.1.7 on 2019-07-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_app', '0009_auto_20190712_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='time',
        ),
    ]
