# Generated by Django 2.1.7 on 2019-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_app', '0010_remove_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='timee',
            field=models.TextField(blank=True, default='1398-04-21', max_length=20, null=True),
        ),
    ]
