# Generated by Django 2.1.7 on 2019-07-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_app', '0011_news_timee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timee',
            field=models.TextField(blank=True, default='1398-04-21', max_length=12, null=True),
        ),
    ]
