# Generated by Django 2.1.7 on 2019-07-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_app', '0012_auto_20190712_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timee',
            field=models.TextField(blank=True, default='1398-04-22', max_length=12, null=True),
        ),
    ]
