# Generated by Django 2.2 on 2019-05-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190508_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shomare_shenasname',
        ),
    ]
