# Generated by Django 2.2 on 2019-05-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_shomare_shenasname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
