# Generated by Django 2.1.7 on 2019-05-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190508_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
