# Generated by Django 2.1.7 on 2019-05-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_picture2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='Dir_name'),
        ),
    ]
