# Generated by Django 2.1.7 on 2019-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190515_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.ImageField(default='', upload_to='pic_folder/'),
        ),
    ]
