# Generated by Django 2.1.7 on 2019-05-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190515_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.TextField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_history',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
